import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { v4 as uuid } from 'uuid';
import { tokenizeWord, highlightText } from '../../../shared/phonicsEngine.js';
import { config } from '../config.js';

/**
 * Generate an A4 PDF storybook with illustration, grapheme tiles, and IPA strip.
 */
export async function generateStoryPdf(story) {
  const dir = path.join(config.storageDir, 'pdfs');
  fs.mkdirSync(dir, { recursive: true });
  const filename = `${story.id || uuid()}.pdf`;
  const filepath = path.join(dir, filename);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    doc.fillColor('#1B4332').fontSize(22).text('Properly Storybook', { align: 'left' });
    doc.moveDown(0.3);
    doc.fillColor('#3D405B').fontSize(16).text(story.title || 'My Story');
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor('#6B705C').text(
      `Letters and Sounds · Phase ${story.phase} · Theme: ${story.theme || 'adventure'}`,
    );
    doc.moveDown(0.8);

    // Illustration if local file
    if (story.illustrationUrl) {
      const local = path.join(
        config.storageDir,
        story.illustrationUrl.replace(/^\/storage\//, ''),
      );
      if (fs.existsSync(local) && !local.endsWith('.svg')) {
        try {
          doc.image(local, { fit: [500, 280], align: 'center' });
          doc.moveDown(0.8);
        } catch {
          /* skip */
        }
      } else {
        doc.rect(48, doc.y, 500, 160).fillAndStroke('#E9F5DB', '#95D5B2');
        doc.fillColor('#1B4332').fontSize(12).text('Illustration', 60, doc.y - 140);
        doc.moveDown(6);
      }
    }

    doc.fillColor('#1B4332').fontSize(13).text(story.text || '', { lineGap: 6 });
    doc.moveDown(1.2);

    doc.fontSize(12).fillColor('#3D405B').text('Grapheme tiles & IPA phoneme strip');
    doc.moveDown(0.5);

    const words = highlightText(story.text || '', story.phase).filter((p) => p.type === 'word');
    let x = doc.page.margins.left;
    let y = doc.y;
    const maxX = doc.page.width - doc.page.margins.right;

    for (const w of words.slice(0, 40)) {
      const tiles = w.tiles?.length ? w.tiles : tokenizeWord(w.value);
      const blockWidth = Math.max(40, tiles.length * 22);
      if (x + blockWidth > maxX) {
        x = doc.page.margins.left;
        y += 52;
      }
      let tx = x;
      for (const t of tiles) {
        if (!t.grapheme) continue;
        doc.roundedRect(tx, y, 20, 22, 3).fillAndStroke(t.color || '#888', '#333');
        doc.fillColor('#fff').fontSize(9).text(t.grapheme, tx + 2, y + 6, { width: 16, align: 'center' });
        doc.fillColor('#333').fontSize(7).text(t.ipa || '', tx, y + 24, { width: 20, align: 'center' });
        tx += 22;
      }
      x = tx + 10;
    }

    doc.moveDown(4);
    doc.fontSize(9).fillColor('#6B705C').text('Generated by Properly · Mrs Owl · For home practice', {
      align: 'center',
    });

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return {
    path: filepath,
    url: `/storage/pdfs/${filename}`,
  };
}
